/*
 * 
 *  Class that will act as a tuple that will represent a private
 *  key generated by the RSA algorithm
 *  
 */
package Securitypkg;
import java.math.BigInteger;

class PrivateKey
{
	// key, val pair for decryption
	private BigInteger n;
	private BigInteger d;
	
	// Constructor
	// @Param - n = computed by the the given prime numbers  p and q
	// @Param - e = computed through extended euclidian algorithm(big values) or through trial and error(small values)
	public PrivateKey(BigInteger n, BigInteger d)
	{
		this.n = n;
		this.d = d;
	}
	
	// getter
	public BigInteger getN()
	{
		return n;
	}
	
	// getter
	public BigInteger getD()
	{
		return d;
	}
	
}
